package models

import "gorm.io/gorm"

func Migrate(db *gorm.DB) {
	db.Migrator().DropTable(&Wallet{})
	db.Migrator().DropTable(&CreditCard{})
	db.Migrator().DropTable(&Bank{})
	db.Migrator().DropTable(&Questions{})
	db.Migrator().DropTable(&User{})
	db.Migrator().DropTable(&PersonalSecurityQuestion{})
	db.Migrator().DropTable(&UsedPromo{})
	db.Migrator().DropTable(&Promo{})
	db.Migrator().DropTable(&Location{})
	db.Migrator().DropTable(&Hotel{})
	db.Migrator().DropTable(&RoomType{})
	db.Migrator().DropTable(&ReviewType{})
	db.Migrator().DropTable(&Review{})
	db.Migrator().DropTable(&Airport{})
	db.Migrator().DropTable(&Flight{})
	db.Migrator().DropTable(&Airline{})
	db.Migrator().DropTable(&SearchHistory{})
	db.Migrator().DropTable(&Search{})
	db.Migrator().DropTable(&CartHotelTicket{})
	db.Migrator().DropTable(&ReservedSeat{})
	db.Migrator().DropTable(&CartFlightTicket{})
	db.Migrator().DropTable(&FlightTicket{})
	db.Migrator().DropTable(&HotelTicket{})

	db.AutoMigrate(&Wallet{})
	db.AutoMigrate(&CreditCard{})
	db.AutoMigrate(&Bank{})
	db.AutoMigrate(&Questions{})
	db.AutoMigrate(&User{})
	db.AutoMigrate(&PersonalSecurityQuestion{})
	db.AutoMigrate(&UsedPromo{})
	db.AutoMigrate(&Promo{})
	db.AutoMigrate(&Location{})
	db.AutoMigrate(&Hotel{})
	db.AutoMigrate(&RoomType{})
	db.AutoMigrate(&ReviewType{})
	db.AutoMigrate(&Review{})
	db.AutoMigrate(&Airport{})
	db.AutoMigrate(&Flight{})
	db.AutoMigrate(&Airline{})
	db.AutoMigrate(&SearchHistory{})
	db.AutoMigrate(&Search{})
	db.AutoMigrate(&CartHotelTicket{})
	db.AutoMigrate(&ReservedSeat{})
	db.AutoMigrate(&CartFlightTicket{})
	db.AutoMigrate(&FlightTicket{})
	db.AutoMigrate(&HotelTicket{})
}
